version: "2"
run:
  concurrency: 4
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - interfacebloat
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nestif
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  disable:
    - depguard
  settings:
    funlen:
      lines: 66
      statements: 45
    gocognit:
      min-complexity: 40
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gosec:
      excludes:
        - G115
    interfacebloat:
      max: 20
    lll:
      line-length: 120
      tab-width: 4
    nestif:
      min-complexity: 20
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Allow long test functions
      - path: _test\.go
        linters:
          - funlen
      # Allow fmt.Print in CLI tool
      - path: cmd/voice/
        linters:
          - forbidigo
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
