version: "2"
run:
  concurrency: 4
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  disable:
    - depguard
  settings:
    funlen:
      lines: 66
      statements: 45
    gocognit:
      min-complexity: 40
    godox:
      keywords:
        - HACK
        - FIXME
    gosec:
      excludes:
        - G115
    interfacebloat:
      max: 20
    lll:
      line-length: 120
      tab-width: 4
    nestif:
      min-complexity: 20
    nlreturn:
      block-size: 7
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
